name: codacy-coverage
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        checks: write
    steps:
    - uses: actions/checkout@v3
    - name: Upload coverage reports to Codacy
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh)
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}  