name: ⛱️ codecov
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        checks: write
    steps:
    - uses: actions/checkout@v4
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}